### ISSUE TITLE
$modal is not a function

### ISSUE THREAD

**Issue by dethline** [mgcrea/angular-strap#2277]
angular.js:14940 TypeError: $modal is not a function
    at AlertFactory (angular-strap.js:4268)

angularJS 1.7.1
bootstrap 3.3.7
angular-strap 2.3.12

usage:

var myAlert = $alert({title: 'Logged in!',
                         content:message+' Redirecting...',
                         placement: 'top', type: 'success',
                         show: true,'duration':2,
                         container:'#message_container'
                    });

**Comment by dethline** [comment]
Works with angularJS 1.6.5.
