### ISSUE TITLE
modal window not working in plunker live demo from docs page

### ISSUE THREAD

**Issue by aldarund** [mgcrea/angular-strap#1670]
http://mgcrea.github.io/angular-strap/#/modals
When i click live demo plunker it creates a plunker.
But then it doesn't really work.
When i click simple modal from object - it works, but not the same way as it on docs page. The screen around the modal become not transparent but a black ( im trying to use it in my project, and have exactly same issue, so i wanted to try plunker from docs too see where im wrong, but it have same black background instead of transparent like in docs)
And when i click custom modal its even worse. It dont work at all. It gives js error:

Uncaught TypeError: modalLinker is not a functionModalFactory.
$modal.show @ angular-strap.js:1851ModalFactory.
$modal.toggle @ angular-strap.js:1920
c @ angular.js:3011

I tried in chrome and firefox. Same behaviour.

**Comment by vmlf01** [comment]
Caused by #1660

**Comment by vmlf01** [comment]
Sorry, I forgot to address your original issue. You need custom CSS for the animation and transparent background on the modals, which in the case of the docs site are provided by Angular Motion and Bootstrap Additions projects.

You can see a sample LESS/SASS definition in the docs under Backdrop animation of the modal section.
