### ISSUE TITLE
Typeahead remote source error with angular 1.4 & angular-strap 2.2.1

### ISSUE THREAD

**Issue by cyp3rius** [mgcrea/angular-strap#1684]
I saw reported bug about  Angular 1.4 support #1659 and `TypeError: options.domOperation is not a function` issue. I've got it with all my Typeaheads calling for remote sources and also after each response I've got:

```
"Error: [filter:notarray] http://errors.angularjs.org/1.4.0-rc.1/filter/notarray?p0=%7B%22%24%24state%22%3A%7B%22status%22%3A1%2C%22value%22%3A%5B%7B%22id%22%3A1%2C%22name%22%3A%22Krzysztof%20Kowalski%22%7D%2C%7B%22id%22%3A2%2C%22name%22%3A%22Grzegorz%20Sosna%22%7D%5D%7D%7D
G/<@http://localhost:9000/assets/lib/angularjs/angular.min.js:6:421
Uf/<@http://localhost:9000/assets/lib/angularjs/angular.min.js:148:189
anonymous/fn@http://localhost:9000/assets/lib/angularjs/angular.min.js line 208 > Function:2:304
ParseOptionsFactory/$parseOptions.valuesFn@http://localhost:9000/assets/lib/angular-strap/angular-strap.js:2354:26
postLink/<@http://localhost:9000/assets/lib/angular-strap/angular-strap.js:4462:11
cf/this.$get</m.prototype.$digest@http://localhost:9000/assets/lib/angularjs/angular.min.js:129:481
cf/this.$get</m.prototype.$apply@http://localhost:9000/assets/lib/angularjs/angular.min.js:132:497
rg</this.$$debounceViewValueCommit@http://localhost:9000/assets/lib/angularjs/angular.min.js:260:210
rg</this.$setViewValue@http://localhost:9000/assets/lib/angularjs/angular.min.js:259:460
gb/l@http://localhost:9000/assets/lib/angularjs/angular.min.js:162:1
m.event.dispatch@http://localhost:9000/assets/lib/jquery/jquery.min.js:3:8497
m.event.add/r.handle@http://localhost:9000/assets/lib/jquery/jquery.min.js:3:5235
" angular.min.js:106:324
```

Results returned by .then(...) is in 100% Arrays (works on production app with angular 1.3.15 and angular strap 2.1.2). Now I've updated angular to 1.4 rc1 and angular-strap to 2.2.1.

**Comment by gitawego** [comment]
I get this error as well with v2.2.3 for directive bs-select in angular 1.4

```
Uncaught TypeError: options.domOperation is not a functionclose 
@ angular-animate.js:2803(anonymous function) 
@ angular-animate.js:2627(anonymous function) 
@ angular-animate.js:2515forEach 
@ angular.js:336AnimateRunner._resolve 
@ angular-animate.js:2514(anonymous function) 
@ angular-animate.js:2507$$rAFMutexFactory 
@ angular-animate.js:2383AnimateRunner.complete 
@ angular-animate.js:2506close 
@ angular-animate.js:1026onAnimationProgress 
@ angular-animate.js:1221jQuery.event.dispatch 
```

**Comment by capaj** [comment]
fix for filter:notaray is here: https://github.com/mgcrea/angular-strap/pull/1711

**Comment by vmlf01** [comment]
Duplicate #1567 and #1659
