### ISSUE TITLE
TypeError: scope.$activeIndex.indexOf is not a function

### ISSUE THREAD

**Issue by nicklasb** [mgcrea/angular-strap#1652]
Hi, 

I have this strange problem. I am trying to make [angular-schema-form-dynamic-select](https://github.com/OptimalBPM/angular-schema-form-dynamic-select/tree/angular-strap_221_compat) work with 2.2.1. 

I have two identical selects, one loads the items dynamically in an ng-init, as shown below, and the other gets them preloaded in a variable.
The *only* difference between the two is the `ng-init="fetchResult(form.options)"`.
 If I have the items in a variable, it works, if I load them dynamically as displayed, I am rewarded with the error message further down when I click the drop down.

The dropdown is displayed, and all items are there, but clicking them results in nothing.

(if your eyes are drawn to [$$value$$ i *think* that is not relevant here](https://github.com/Textalk/angular-schema-form/blob/development/docs/extending.md#the-magic-value), as that is present on both alternatives, I have also tried removing filters and stuff like that)

    <div ng-init="mainScope=this.$parent.$parent;" class="form-group {{form.htmlClass}}"
         ng-class="{'has-error': hasError(), 'has-success': hasSuccess()}">
        <label class="control-label {{form.labelHtmlClass}}" ng-show="showTitle()">{{form.title}}</label>
    
        <div class="form-group {{form.fieldHtmlClass}}" ng-controller="StrapSelectController" ng-init="fetchResult(form.options)">
            <button type="button" class="btn btn-default" sf-changed="form" schema-validate="form" ng-model="$$value$$"
                    data-placeholder="{{form.placeholder || form.schema.placeholder || ('placeholders.select')}}" data-html="1" data-multiple="1"
                    bs-options="item.value as item.text for item in form.items | selectFilter:form:mainScope:this"
                    bs-select>
            </button>
            <span class="help-block">{{ (hasError() && errorMessage(schemaError())) || form.description}}</span>
        </div>
    </div>

The error:
    
    TypeError: scope.$activeIndex.indexOf is not a function
        at Object.angular.module.provider.$get.$select.$isActive (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular-strap/dist/angular-strap.js:3376:39)
        at Scope.angular.module.provider.$get.scope.$isActive (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular-strap/dist/angular-strap.js:3296:26)
        at $parseFunctionCall (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular/angular.js:12404:18)
        at extend.&& (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular/angular.js:11804:66)
        at Object.$parseBinaryFn [as get] (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular/angular.js:12130:14)
        at Scope.$get.Scope.$digest (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular/angular.js:14300:40)
        at safeDigest (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular-strap/dist/angular-strap.js:5211:72)
        at angular.module.provider.$get.$tooltip.hide (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular-strap/dist/angular-strap.js:4802:11)
        at Object.angular.module.provider.$get.$select.hide (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular-strap/dist/angular-strap.js:3455:11)
        at HTMLButtonElement.angular.module.provider.$get.$tooltip.leave (http://localhost:63342/angular-schema-form-dynamic-select/bower_components/angular-strap/dist/angular-strap.js:4772:29)
      (anonymous function)	
      $get	
      $get.Scope.$digest	
      safeDigest	
      angular.module.provider.$get.$tooltip.hide	
      angular.module.provider.$get.$select.hide	
      angular.module.provider.$get.$tooltip.leave	
      eventHandler	

I have seen that other have gotten the same error message when navigating.
Anyway, this did not happen in 2.1.6. 

Any ideas?

**Comment by vmlf01** [comment]
Have you tried using the fetchResult directly in the bs-options expression instead of using ng-init? I think it supports async data sources if it returns a promise.

**Comment by nicklasb** [comment]
Hi!

No I haven't, but on the other hand, fetchResult doesn't return a promise, but sets the items property that then is used. It employs a number of different ways of fetching data behind the scenes. 
And sync, async or directly from a variable doesn't matter, I am getting the exact same error anyway.

I am not sure, but it feels like one now have to do something more than in 2.1.6 when one changes the list items  after initialization, like setting the $activeIndex variable or setting.

Thanks for your response!

**Comment by vmlf01** [comment]
Can you post a plunker with your sample? Something people can experiment?

**Comment by nicklasb** [comment]
Ok, this was an error on my side.
As always in these cases when something seems to be something, it is something else. 
Sorry, the culprit *was* $$value$$ after all, it doesn't seem to initialize in the exact same moment now, something has changed in some underlying library, so there was no model assigned.

So to conclude, a non-set $activeIndex seems to be related to the model being unset.

Closing.

**Comment by jboelter** [comment]
For anyone else that runs into this ...  I ran into a similar issue w/ 2.2.1.  Turns out that binding to an undefined element wasn't working while it was being loaded (async request for the data).


```html
<button bs-select data-multiple="1" ng-model="foo.items" ... />
```

Works:
```javascript
$scope.foo.items = [];
```

Fails:
```javascript
$scope.foo.items = undefined;
```

**Comment by nicklasb** [comment]
Related to this?
https://github.com/mgcrea/angular-strap/issues/1654

**Comment by jboelter** [comment]
Just pulled 2.2.2 and confirmed it's fixed w/o the workaround.

**Comment by nicklasb** [comment]
Ok, would like to add to this thread that this actual issue was not related to stuff being undefined but to the fact that I had made a mistake when using angular-schema-form.
The actual uninitialized model-issue was handled and resolved in issue https://github.com/mgcrea/angular-strap/issues/1654 and the consecutive pull requests.
